build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\cocur\background-process

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%

environment:
  matrix:
    - COMPOSER_FLAGS: ""

install:
  - cinst -y OpenSSL.Light
  - cinst -y php --ignore-dependencies
  - cd c:\tools\php72
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo memory_limit=1G >> php.ini
  - cd c:\projects\cocur\background-process
  - refreshenv
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar update %COMPOSER_FLAGS% --no-interaction --no-progress

test_script:
  - cd c:\projects\cocur\background-process
  - vendor\bin\phpunit.bat --verbose
